name: testing
description: Testing
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_framework: ^0.1.4
  google_fonts: ^6.2.1
  animations: ^2.0.11
  pin_code_text_field: ^1.8.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.23.0+1
  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0
  modal_bottom_sheet: ^3.0.0
  url_launcher: ^6.0.12
  fluttertoast: ^8.0.8
  introduction_screen: ^3.1.14
  package_info_plus: ^8.1.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
